### ISSUE TITLE
Label is not available in plugin options (but placeholder is)

### ISSUE THREAD

**Issue by Tofandel** [yogakurniawan/vue-tel-input-vuetify#10]
The label prop is not taken from the plugin options, this is inconsistent behavior and it should be configurable like placeholder is

```js
Vue.use(VueTelInputVuetify, {
  vuetify,
  placeholder: '',
  label: 'Phone'
});
```

**Comment by yogakurniawan** [comment]
@Tofandel i have fixed this issue. can you check if this issue solved ?

**Comment by Tofandel** [comment]
Nope it's still missing in the props of the component
```js
    label: {
      type: String,
      default: 'Enter a Phone Number',
    },
    placeholder: {
      type: String,
      default: () => getDefault('placeholder'),
    },
```

Should be
```js
    label: {
      type: String,
      default: () => getDefault('label'),
    },
    placeholder: {
      type: String,
      default: () => getDefault('placeholder'),
    },
```

**Comment by yogakurniawan** [comment]
okay it's fixed now in version **1.2.6**

**Comment by yogakurniawan** [comment]
closing this issue
